# Generated by Django 3.2.18 on 2023-09-10 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RollbackNodeSnapshot",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("root_pipeline_id", models.CharField(max_length=64, verbose_name="root pipeline id")),
                ("node_id", models.CharField(max_length=64, verbose_name="node_id")),
                ("code", models.CharField(max_length=64, verbose_name="node_code")),
                ("version", models.CharField(max_length=33, verbose_name="状态版本")),
                ("inputs", models.TextField(verbose_name="节点执行输入数据")),
                ("outputs", models.TextField(verbose_name="节点执行输出数据")),
                ("context_values", models.TextField(verbose_name="pipeline context values")),
                ("rolled_back", models.BooleanField(default=False, verbose_name="节点是否已经回滚过")),
            ],
        ),
        migrations.CreateModel(
            name="RollbackPlan",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("root_pipeline_id", models.CharField(max_length=64, verbose_name="root pipeline id")),
                ("start_node_id", models.CharField(max_length=64, verbose_name="start node id")),
                ("target_node_id", models.CharField(max_length=64, verbose_name="target_node_id")),
                ("is_expired", models.BooleanField(default=False, verbose_name="is expired")),
            ],
        ),
        migrations.CreateModel(
            name="RollbackSnapshot",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("root_pipeline_id", models.CharField(max_length=64, verbose_name="root pipeline id")),
                ("graph", models.TextField(verbose_name="本次回滚的拓扑信息")),
                ("node_access_record", models.TextField(verbose_name="本次回滚的节点访问信息")),
                ("skip_rollback_nodes", models.TextField(verbose_name="skip rollback nodes")),
                ("start_node_id", models.CharField(max_length=64, verbose_name="start node id")),
                ("target_node_id", models.CharField(max_length=64, verbose_name="target_node_id")),
                ("is_expired", models.BooleanField(default=False, verbose_name="是否已经过期")),
            ],
        ),
        migrations.CreateModel(
            name="RollbackToken",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("root_pipeline_id", models.CharField(max_length=64, verbose_name="root pipeline id")),
                ("token", models.TextField(verbose_name="token信息")),
                ("is_deleted", models.BooleanField(default=False, help_text="表示当前实例是否删除", verbose_name="是否已经删除")),
            ],
        ),
    ]
