# Generated by Django 3.2.18 on 2023-08-18 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RollbackToken",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("root_pipeline_id", models.CharField(max_length=64, verbose_name="root pipeline id")),
                ("token", models.TextField(verbose_name="token信息")),
                ("is_deleted", models.BooleanField(default=False, help_text="表示当前实例是否删除", verbose_name="是否已经删除")),
            ],
        ),
    ]
