# -*- coding: utf-8 -*-


class EventType(object):
    NODE_CALLBACK = "NODE_CALLBACK"
    SCHEDULE_DUE = "SCHEDULE_DUE"
    SUBPROCESS_FINISH = "SUBPROCESS_FINISH"
    PROCESS_WAKEUP = "PROCESS_WAKEUP"
    AUTO_RECOVERY = "AUTO_RECOVERY"
    MANUAL_RECOVERY = "MANUAL_RECOVERY"


class EventStatus(object):
    PENDING = "PENDING"
    PROCESSING = "PROCESSING"
    APPLIED = "APPLIED"
    OBSOLETE = "OBSOLETE"
    MANUAL_REQUIRED = "MANUAL_REQUIRED"
    SHADOW_MISMATCH = "SHADOW_MISMATCH"


class EventMode(object):
    SHADOW = "SHADOW"
    ACTIVE = "ACTIVE"


class ErrorCode(object):
    LEASE_BUSY = "LEASE_BUSY"
    TEMP_ERROR = "TEMP_ERROR"
    CONTRADICTION = "CONTRADICTION"
