# Generated by Django 2.2.24 on 2022-01-12 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0031_auto_20210624_2317'),
    ]

    operations = [
        migrations.AddField(
            model_name='templaterelationship',
            name='scheme_id_list',
            field=models.TextField(default='', verbose_name='子流程引用的执行方案ID列表'),
        ),
    ]
