# Generated by Django 2.2.24 on 2022-01-10 14:42

from django.db import migrations
import pipeline.models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0031_auto_20210624_2317'),
    ]

    operations = [
        migrations.AddField(
            model_name='templaterelationship',
            name='subproces_use_scheme_ids',
            field=pipeline.models.CompressJSONField(blank=True, null=True, verbose_name='子流程引用的执行方案ID列表'),
        ),
    ]
