# -*- coding: utf-8 -*-
# Generated by Codex for pipeline diagnostics initial models.

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import pipeline.contrib.diagnostics.models


class Migration(migrations.Migration):

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DiagnosticEvent",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False, verbose_name="ID")),
                ("event_type", models.CharField(db_index=True, max_length=64, verbose_name="事件类型")),
                ("root_pipeline_id", models.CharField(db_index=True, max_length=64, verbose_name="根 Pipeline ID")),
                (
                    "node_id",
                    models.CharField(blank=True, db_index=True, default="", max_length=64, verbose_name="节点ID"),
                ),
                ("process_id", models.BigIntegerField(blank=True, db_index=True, null=True, verbose_name="进程ID")),
                ("version", models.CharField(blank=True, default="", max_length=64, verbose_name="节点版本")),
                ("schedule_id", models.BigIntegerField(blank=True, db_index=True, null=True, verbose_name="调度ID")),
                (
                    "callback_data_id",
                    models.BigIntegerField(blank=True, db_index=True, null=True, verbose_name="回调数据ID"),
                ),
                (
                    "result",
                    models.CharField(blank=True, db_index=True, default="", max_length=32, verbose_name="事件结果"),
                ),
                ("reason", models.TextField(blank=True, default="", verbose_name="诊断原因")),
                ("duration", models.FloatField(blank=True, null=True, verbose_name="持续时间")),
                (
                    "engine_version",
                    models.CharField(blank=True, default="", max_length=64, verbose_name="引擎版本"),
                ),
                (
                    "payload",
                    pipeline.contrib.diagnostics.models.JSONTextField(default=dict, verbose_name="诊断载荷"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="创建时间")),
            ],
            options={
                "verbose_name": "Pipeline诊断事件",
                "verbose_name_plural": "Pipeline诊断事件",
                "ordering": ["-id"],
                "index_together": {("root_pipeline_id", "node_id"), ("event_type", "result")},
            },
        ),
        migrations.CreateModel(
            name="DiagnosticCase",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False, verbose_name="ID")),
                ("root_pipeline_id", models.CharField(db_index=True, max_length=64, verbose_name="根 Pipeline ID")),
                ("node_id", models.CharField(db_index=True, max_length=64, verbose_name="节点ID")),
                ("stuck_type", models.CharField(db_index=True, max_length=64, verbose_name="卡住类型")),
                (
                    "severity",
                    models.CharField(
                        choices=[("info", "提示"), ("warning", "告警"), ("critical", "严重")],
                        db_index=True,
                        default="info",
                        max_length=32,
                        verbose_name="严重级别",
                    ),
                ),
                ("confidence", models.FloatField(default=0.0, verbose_name="置信度")),
                (
                    "status",
                    models.CharField(
                        choices=[("open", "待治理"), ("resolved", "已解决"), ("ignored", "已忽略")],
                        db_index=True,
                        default="open",
                        max_length=32,
                        verbose_name="治理状态",
                    ),
                ),
                (
                    "first_seen_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, db_index=True, verbose_name="首次发现时间"
                    ),
                ),
                (
                    "last_seen_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, db_index=True, verbose_name="最近发现时间"
                    ),
                ),
                ("hit_count", models.IntegerField(default=1, verbose_name="命中次数")),
                (
                    "evidence",
                    pipeline.contrib.diagnostics.models.JSONTextField(default=dict, verbose_name="证据"),
                ),
                (
                    "related_objects",
                    pipeline.contrib.diagnostics.models.JSONTextField(default=dict, verbose_name="关联对象"),
                ),
                (
                    "recommended_actions",
                    pipeline.contrib.diagnostics.models.JSONTextField(default=list, verbose_name="推荐操作"),
                ),
                (
                    "forbidden_actions",
                    pipeline.contrib.diagnostics.models.JSONTextField(default=list, verbose_name="禁止操作"),
                ),
                ("message", models.TextField(blank=True, default="", verbose_name="诊断信息")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="创建时间")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
            ],
            options={
                "verbose_name": "Pipeline诊断案例",
                "verbose_name_plural": "Pipeline诊断案例",
                "ordering": ["-id"],
                "index_together": {("root_pipeline_id", "node_id", "stuck_type", "status"), ("status", "severity")},
                "unique_together": {("root_pipeline_id", "node_id", "stuck_type", "status")},
            },
        ),
        migrations.CreateModel(
            name="DiagnosticOperationAudit",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "operation_type",
                    models.CharField(
                        db_index=True,
                        max_length=64,
                        verbose_name="操作类型",
                    ),
                ),
                (
                    "target_object",
                    pipeline.contrib.diagnostics.models.JSONTextField(default=dict, verbose_name="操作对象"),
                ),
                ("operator", models.CharField(max_length=64, verbose_name="操作人")),
                (
                    "mode",
                    models.CharField(
                        choices=[("dry_run", "预检查"), ("apply", "执行")],
                        db_index=True,
                        default="dry_run",
                        max_length=32,
                        verbose_name="操作模式",
                    ),
                ),
                (
                    "precheck_result",
                    pipeline.contrib.diagnostics.models.JSONTextField(default=dict, verbose_name="预检查结果"),
                ),
                (
                    "result",
                    pipeline.contrib.diagnostics.models.JSONTextField(default=dict, verbose_name="操作结果"),
                ),
                (
                    "risk_level",
                    models.CharField(
                        choices=[("low", "低"), ("medium", "中"), ("high", "高")],
                        db_index=True,
                        default="low",
                        max_length=32,
                        verbose_name="风险级别",
                    ),
                ),
                (
                    "payload",
                    pipeline.contrib.diagnostics.models.JSONTextField(default=dict, verbose_name="操作载荷"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="创建时间")),
                (
                    "case",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="operation_audits",
                        to="pipeline_diagnostics.DiagnosticCase",
                        verbose_name="诊断案例",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pipeline诊断操作审计",
                "verbose_name_plural": "Pipeline诊断操作审计",
                "ordering": ["-id"],
                "index_together": {("operator", "operation_type"), ("mode", "created_at")},
            },
        ),
    ]
