name: Engine Flake8 and Black

on:
  workflow_call:

jobs:
  flake8_and_black:

    runs-on: ubuntu-22.04

    strategy:
      matrix:
        python-version: [3.6.12, 3.7.16]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }} with pyenv
      run: .github/scripts/setup_pyenv_python.sh ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8==4.0.1 black==20.8b1
    - name: Lint with flake8
      run: |
        flake8 bamboo_engine/
    - name: Format with black
      run: |
        black bamboo_engine/
