name: PR check

on:
  pull_request:
    branches: [master, develop]

jobs:
  engine-lint:
    uses: ./.github/workflows/engine_flake8_and_black.yml

  pipeline-lint:
    uses: ./.github/workflows/runtime_pipeline_flake8_and_black.yml

  engine-unittest:
    needs: engine-lint
    uses: ./.github/workflows/engine_unittest.yml

  pipeline-unittest:
    needs: pipeline-lint
    uses: ./.github/workflows/runtime_pipeline_unittest.yml
  
  runtime-pipeline-intergration-test:
    needs: [engine-unittest, pipeline-unittest]
    uses: ./.github/workflows/runtime_pipeline_end_to_end_test.yml
  
  pipeline-intergration-test:
    needs: pipeline-unittest
    uses: ./.github/workflows/pipeline_end_to_end_test.yml
