name: PR check example

on:
  pull_request:
    branches: [ master ]

jobs:
  engine_lint:
    uses: TencentBlueKing/bamboo-engine/.github/workflows/engine_flake8_and_black.yml@main

  pipeline_lint:
    uses: TencentBlueKing/bamboo-engine/.github/workflows/runtime_pipeline_flake8_and_black.yml@main

  engine_test:
    uses: TencentBlueKing/bamboo-engine/.github/workflows/engine_unittest.yml@main

   
  pipeline_test:
    uses: TencentBlueKing/bamboo-engine/.github/workflows/runtime_pipeline_unittest.yml@main
