name: PR check example

on:
  pull_request:
    branches: [ master ]

jobs:
  engine_lint:
    name: Engine code lint
    runs-on: ubuntu-latest
    steps:
      - name: code-lint
        uses: ./.github/workflows/engine_flake8_and_black

  pipeline_lint:
    name: Pipeline code lint
    runs-on: ubuntu-latest
    steps:
      - name: code-lint
        uses: ./.github/workflows/runtime_pipeline_flake8_and_black

  engine_test:
    name: Engine relate test
    runs-on: ubuntu-latest
    steps:
      - name: unittest
        uses: ./.github/workflows/myengine_unittest

   
  pipeline_test:
    name: Pipeline relate test
    runs-on: ubuntu-latest
    steps:
      - name: unittest
        uses: ./.github/workflows/runtime_pipeline_unittest
      - name: runtime pipeline end to end test
        uses: ./.github/workflows/runtime_pipeline_end_to_end_test
      - name: pipeline end to end test
        uses: ./.github/workflows/pipeline_end_to_end_test
