name: PR check example

on:
  pull_request:
    branches: [ master ]

jobs:
  engine_lint:
    uses: TencentBlueKing/bamboo-engine/.github/workflows/engine_flake8_and_black.yml@master

  pipeline_lint:
    uses: TencentBlueKing/bamboo-engine/.github/workflows/runtime_pipeline_flake8_and_black.yml@master

  engine_test:
    uses: TencentBlueKing/bamboo-engine/.github/workflows/engine_unittest.yml@master

   
  pipeline_test:
    uses: TencentBlueKing/bamboo-engine/.github/workflows/runtime_pipeline_unittest.yml@master
