name: PR check

on:
  pull_request:
    branches: [ master ]

jobs:
  Engine lint:
    uses: TencentBlueKing/bamboo-engine/.github/workflows/engine_flake8_and_black.yml@master

  Pipeline lint:
    uses: TencentBlueKing/bamboo-engine/.github/workflows/runtime_pipeline_flake8_and_black.yml@master

  Engine test:
    uses: TencentBlueKing/bamboo-engine/.github/workflows/engine_unittest.yml@master

  Runtime pipeline test:
    steps:
      - uses: TencentBlueKing/bamboo-engine/.github/workflows/runtime_pipeline_unittest.yml@master
      - uses: TencentBlueKing/bamboo-engine/.github/workflows/runtime_pipeline_end_to_end_test.yml@master

  Pipeline test:
    steps:
      - uses: TencentBlueKing/bamboo-engine/.github/workflows/runtime_pipeline_unittest.yml@master
      - uses: TencentBlueKing/bamboo-engine/.github/workflows/pipeline_end_to_end_test.yml@master
