name: PR check example

on:
  pull_request:
    branches: [ master ]

jobs:
  engine_lint:
    name: code-lint
    uses: github.com/TencentBlueKing/.github/workflows/engine_flake8_and_black.yml

  pipeline_lint:
    name: code-lint
    uses: github.com/TencentBlueKing/.github/workflows/runtime_pipeline_flake8_and_black.yml

  engine_test:
    name: unittest
    uses: github.com/TencentBlueKing/.github/workflows/myengine_unittest.yml

   
  pipeline_test:
    name: Pipeline relate test
    uses: github.com/TencentBlueKing/.github/workflows/runtime_pipeline_unittest.yml
