name: Runtime Pipeline python package
on:
  push:
    tags:
      - "bamboo-pipeline-v*.*.*"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.7
        uses: actions/setup-python@v5
        with:
          python-version: "3.7"

      - name: Install Poetry
        run: python -m pip install "poetry==1.5.1"

      - name: Remove Test Code
        run: |
          cd runtime/bamboo-pipeline
          rm -rf pipeline/django_signal_valve/tests
          rm -rf pipeline/tests
          rm -rf pipeline/contrib/external_plugins/tests
          poetry build -vvv
          poetry config pypi-token.pypi ${{ secrets.PIPELINE_PYPI_TOKEN }}
          poetry publish
